# -- Site Configuration --

defaultContentLanguage = "en"
theme = "blowfish"
title = "Tech and Lifestyle Blog"
# config/_default/languages.en.toml

[params.author]
bio = "Experienced Python developer with 6+ years of expertise in Django, Flask, and FastAPI, specializing in high-performance web applications. Skilled in Node.js/TypeScript (Express), Docker, CI/CD, and TDD with 95% test coverage. Proven track record across ERP, CRM, e-commerce, blockchain, and AI projects. Focused on continuous growth and delivering impactful, scalable solutions."
headline = "Software Engineer"
image = "/images/static/formal-photo.JPG"
links = [
  {facebook = "https://www.facebook.com/share/1AbxYZPMJD/?mibextid=wwXIfr"},
  {linkedin = "https://www.linkedin.com/in/yalchinmammadli"},
]
name = "Yalchin Mammadli"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

buildDrafts = false
buildFuture = false
enableRobotsTXT = true
showViews = true
summaryLength = 0

enableEmoji = true

googleAnalytics = "G-RGY073DR5F"

[pagination]
pagerSize = 6

[imaging]

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[sitemap]
changefreq = 'daily'
filename = 'sitemap.xml'
priority = 0.5

[outputs]
home = ["HTML", "RSS", "JSON"]

[related]
threshold = 0
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 100

[[related.indices]]
name = "series"
weight = 50

[[related.indices]]
name = "authors"
weight = 20

[[related.indices]]
name = "date"
weight = 10

[[related.indices]]
applyFilter = false
name = 'fragmentrefs'
type = 'fragments'
weight = 10
